### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MCTyler** [ExtendedAlpha/SeparateWorldItems#4] opened 2015-05-25 23:03 UTC
Latest Spigot Build...
[16:01:28 ERROR]: Could not pass event PlayerGameModeChangeEvent to SeparateWorldItems v2.7.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:757) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:353) [Multiverse-Core-2.5.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-17fce80-25de1e6]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at org.json.JSONObject.<init>(JSONObject.java:197) ~[?:?]
        at org.json.JSONObject.<init>(JSONObject.java:324) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:64) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:60) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.GameModeChangeEventListener.onPlayerGameModeChange(GameModeChangeEventListener.java:56) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-17fce80-25de1e6]
        ... 12 more

**Comment by TriptychPlaysMC** [comment] 2015-05-25 23:08
I'm going to need you groups.yml and you config.yml and spigot/bukkit version.

**Comment by sgdc3** [comment] 2015-05-25 23:08
It's a problem with the json configuration... Try the latest dev build and delete the configuration file.

**Comment by sgdc3** [comment] 2015-05-25 23:10
Or it may be data corruption in player inventory storage.

**Comment by TriptychPlaysMC** [comment] 2015-05-25 23:16
Wow it is thanks @sgdc3, do what he said.

**Comment by MCTyler** [comment] 2015-05-26 09:41
It was the groups.yml...Thanks

**Comment by sgdc3** [comment] 2015-05-26 13:17
If the problem is resolved, please close the issue. Thanks :)

**Closed** 2015-05-26 15:19 UTC
