### ISSUE TITLE
What's causing this error?

### ISSUE THREAD

**Issue by ssamjh** [ExtendedAlpha/SeparateWorldItems#10] opened 2015-05-26 23:51 UTC
http://pastebin.com/Q31euyMy

**Comment by TriptychPlaysMC** [comment] 2015-05-27 00:16
My best guess is that your default settings.json got corrupted you will need to delete it and restart your server.

**Comment by sgdc3** [comment] 2015-05-27 10:18
I think we need a proper message when there is a configuration error, for example <red><bold>Error: invalid syntax in groups.yml! Try deleting it and restart your server!

**Comment by sgdc3** [comment] 2015-05-28 17:44
If the problem is resolved, please close the issue. Thanks :)

**Comment by TriptychPlaysMC** [comment] 2015-05-28 20:14
User has contacted me on spigot issue now fix closed.

**Closed** 2015-05-28 20:13 UTC
Labels: Support
