### ISSUE TITLE
Error with Spigot 1.8.6 - Could not pass event PlayerQuitEvent

### ISSUE THREAD

**Issue by Dennis000903** [ExtendedAlpha/SeparateWorldItems#6] opened 2015-05-26 09:49 UTC
I am getting this error:

Could not pass event PlayerQuitEvent to SeparateWorldItems v2.7.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:346) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:844) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.IllegalArgumentException: World 'Lobby' not found! Could not get group!
        at com.ExtendedAlpha.SWI.Data.WorldManager.getGroupFromWorld(WorldManager.java:77) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.QuitEventListener.onPlayerQuit(QuitEventListener.java:49) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 12 more

**Comment by Dennis000903** [comment] 2015-05-26 10:04
Another Error:

Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.7.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1051) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:241) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at me.messageofdeath.CommandNPC.Listener.NPCListener.onClick(NPCListener.java:52) [CommandNPC.jar:?]
        at me.messageofdeath.CommandNPC.Listener.NPCListener.onRight(NPCListener.java:30) [CommandNPC.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:276) [citizens-2.0.16-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1288) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.IllegalArgumentException: World 'Lobby' not found! Could not get group!
        at com.ExtendedAlpha.SWI.Data.WorldManager.getGroupFromWorld(WorldManager.java:77) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:53) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 50 more

**Comment by sgdc3** [comment] 2015-05-26 12:31
It's a problem with your groups.yml file in the plugin's directory. Try to delete and reconfigure it.

**Comment by Dennis000903** [comment] 2015-05-26 13:09
Okay thanks :3

**Comment by sgdc3** [comment] 2015-05-26 13:13
You're Welcome ;)

**Comment by sgdc3** [comment] 2015-05-26 13:17
If the problem is resolved, please close the issue. Thanks :)

**Comment by Dennis000903** [comment] 2015-05-26 13:20
Yes :3

**Closed** 2015-05-26 13:21 UTC
